### ISSUE TITLE
Is solution configurable?

### ISSUE THREAD

**Issue by evbots** [handshake-org/hs-miner#11]
I see that the miner can return a solution that does not meet the target provided by a handshake node. Is there a way to configure what the miner considers to be a solution? For example: if I want to consider hashes further -or- closer to the target as a solution for submitting shares to a pool.

**Comment by evbots** [comment]
I noticed the method `miner.getPerc()`, which exposes the compile time flag TESTNET_PERC. I bumped this figure to 90 from the default 50 ([found here](https://github.com/handshake-org/hs-miner/blob/27bcb18af6e095382b9e72ce69cde26f5c999cf9/scripts/get#L9)) and rebuilt the miner (`make testnet`). It seems that solutions are found more often. Is this the right figure to be adjusting in order to find solutions closer or farther from the target? @chjj If so, any plans to expose this as a build flag?

**Comment by boymanjor** [comment]
This is now stale due to the change in pow. Closing this now.
