### ISSUE TITLE
"Error: Bad header size."

### ISSUE THREAD

**Issue by karlwhite** [handshake-org/hs-miner#12]
Does miner.js require updating to reflect changes in testnet 3?

```
$ ./hs-miner/bin/hs-miner --rpc-host localhost --rpc-port 13037

Miner params:
  Backend: lean-cuda
  CUDA: true
  Network: testnet
  Edge Bits: 23
  Proof Size: 42
  Easipct: 50

CUDA Devices:
  0: <Tesla M60> 7988903936 256 2505000

Starting miner...
Error: Bad header size.
    at Miner.getWork (/home/ubuntu/hs-miner/bin/miner.js:141:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by karlwhite** [comment]
I have applied the PR to my local miner, and it resolved the error above, however after over 48 hours not a single block has been successfully mined.

Could there be any other updates required to hs-miner that would be required to work with the updated PoW?

**Comment by boymanjor** [comment]
This issue pertains to the old proof of work.
