### ISSUE TITLE
OpenCL backend doesn't adjust local group size

### ISSUE THREAD

**Issue by rhn** [handshake-org/hs-miner#18]
The OpenCL backend takes the block size as the unchanging value:

```
src/opencl.c:264:  size_t local_size = options->blocks;
````

The default results in `CL_INVALID_WORK_ITEM_SIZE (-55)` on `clEnqueueNDRangeKernel`.

The given value should either be adjusted not to exceed `CL_DEVICE_MAX_WORK_GROUP_SIZE` from https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetDeviceInfo.html or the value can be changed to NULL to let the driver decide.

Source: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html

**Comment by boymanjor** [comment]
@rhn thanks for all the issues! I'm closing this only because #16 is already open.
