### ISSUE TITLE
a notebook without GPU, Lenovo T450, can this program to  mining HNS ?

### ISSUE THREAD

**Issue by liubo404** [handshake-org/hs-miner#22]

**Comment by liubo404** [comment]
VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)

**Comment by xiaods** [comment]
yes, you can do it. use CPU miner

**Comment by pinheadmz** [comment]
Technically yes, but the current estimated network hashrate is 33TH/s and a single CPU is unlikely to return any profit. You can mine on testnet for fun if you want to experiment.
