### ISSUE TITLE
why there is padding var in the header?

### ISSUE THREAD

**Issue by rocqina** [handshake-org/hs-miner#24]
I check the source code of hsd. I do not find this.

**Comment by pinheadmz** [comment]
https://github.com/handshake-org/hsd/issues/203

https://github.com/handshake-org/hsd/blob/master/lib/primitives/abstractblock.js#L289-L328

https://gist.githubusercontent.com/pinheadmz/7a54354f528d4db2f7dd09c3d75319ad/raw/74b1cf29838add8c117c842c2d3f3643d4e3499d/hsd_pow.txt

**Comment by rocqina** [comment]
@pinheadmz  Thanks very much.And I find another quesiton about the sumbit from  some hns miner programs like nbminer, gminer . The submit includes nonce and extranonce ,and the length of nonce is 4 bytes,but and the length of extranonce is 4 bytes too. why the length of extranonce is not 24 bytes. Can you help me?

**Comment by pinheadmz** [comment]
You will need to ask your mining pool about that. It sounds like they just aren't using the full extranonce field, which is fine.

**Comment by rocqina** [comment]
OK, Thanks!  Is there  a stratum protocol for hsd  like stratum protocol for btc? I do find the protocol for hsd and how to communicate be tween pool and miner program?

**Comment by pinheadmz** [comment]
Stratum is a huge mess, for all cryptocurrencies. Every mining pool will implement it differently. All of your questions so far really should be directed at the mining pool(s) you want to work with. This repository is an open-source solo-miner without stratum support developed by hsd contributors.

**Comment by rocqina** [comment]
OK. Thank you very much!
