### ISSUE TITLE
Mining before mainnet

### ISSUE THREAD

**Issue by brannondorsey** [handshake-org/hs-miner#6]
Hi there,

I'm interested in participating in securing the HSN by running a miner. However, it is unclear to me whether there is a monetary incentive to do so before the mainnet is launched. Am I correct in assuming that only a HSN testnet exists as of now and thus mining on the testnet will have no effect on the eventual mainnet once it is deployed? Or am I missing something?

Thanks!

**Comment by tynes** [comment]
hey brannon, you are correct that there is only a testnet running currently. mining on the testnet will not transfer over to the mainnet. right now i'd say that the main incentive to mine testnet is to prepare your machine for when mainnet goes live

**Comment by brannondorsey** [comment]
Gotcha, thanks for that clarification. Getting set up before mainnet is not a bad idea. Is mainnet still slated to be launched in September?

**Comment by tynes** [comment]
no problem. i believe so but am not the absolute source of truth
