### ISSUE TITLE
hs-miner will not run

### ISSUE THREAD

**Issue by cyborg-637** [handshake-org/hs-miner#7]
Each time I attempt to run the miner after running hsd, I get the following error:

user@Cyborg-637:~$ ./hs-miner/bin/hs-miner
/home/user/hs-miner/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: libcudart.so.9.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/user/hs-miner/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/user/hs-miner/lib/hs-miner.js:11:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

$ node --version
v8.10.0
$ node --version
v8.10.0

**Comment by tynes** [comment]
It looks like you need to install CUDA. What operating system are you using?

**Comment by cyborg-637** [comment]
Ubuntu 

> It looks like you need to install CUDA. What operating system are you using?

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by cyborg-637** [comment]
I got HS-Miner to GPU mine but it crashes after 5 mins and spits out this error message:

Mining height 17238 (target=010fbc0000000000000000000000000000000000000000000000000000000000).
Mining height 17238 (target=010fbc0000000000000000000000000000000000000000000000000000000000).
Mining height 17238 (target=010fbc0000000000000000000000000000000000000000000000000000000000).

<--- Last few GCs --->

[30041:0x3c44c50]   161695 ms: Scavenge 1386.1 (1423.7) -> 1385.2 (1424.2) MB, 2.1 / 0.0 ms  (average mu = 0.240, current mu = 0.206) allocation failure 
[30041:0x3c44c50]   161702 ms: Scavenge 1386.1 (1424.2) -> 1385.2 (1424.7) MB, 2.4 / 0.0 ms  (average mu = 0.240, current mu = 0.206) allocation failure 
[30041:0x3c44c50]   161707 ms: Scavenge 1386.1 (1424.7) -> 1385.3 (1425.2) MB, 1.9 / 0.0 ms  (average mu = 0.240, current mu = 0.206) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x225bd14dc01d]
Security context: 0x32ae84f1e681 <JSObject>
    1: once [0x32ae84f43449] [events.js:~285] [pc=0x225bd14e709d](this=0x25c0dc9c8169 <WriteStream map = 0xebe606ceee9>,type=0x0a0383c989f1 <String[5]: error>,listener=0x25c0dc9c6b79 <JSFunction noop (sfi = 0x2a0565b76911)>)
    2: log [0x2a0565b786a9] [console.js:~196] [pc=0x225bd14e2556](this=0x25c0dc985309 <Console map = 0xebe606d0331>)
    3: arguments a...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8d1bc0 node::Abort() [hs-miner]
 2: 0x8d1c0c  [hs-miner]
 3: 0xb00bae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [hs-miner]
 4: 0xb00de4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [hs-miner]
 5: 0xeee2b2  [hs-miner]
 6: 0xeee3b8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [hs-miner]
 7: 0xefa4e2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [hs-miner]
 8: 0xefae14 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [hs-miner]
 9: 0xefda81 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [hs-miner]
10: 0xec6fa4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [hs-miner]
11: 0x11660ce v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [hs-miner]
12: 0x225bd14dc01d 
Aborted (core dumped)

**Comment by boymanjor** [comment]
This issue is now out of date. Closing for now.
